"""Changed string length

Revision ID: c2131b13b8cd
Revises: 4edda1dee718
Create Date: 2022-09-13 12:50:38.877662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2131b13b8cd'
down_revision = '4edda1dee718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
